program: routines/size_of_circular_drum.py
project: kac_prediction (circular drum size)
method: random
metric:
  goal: minimize
  name: loss
parameters:
  batch_size:
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 16, 24, 32, 64]
  dropout:
    min: 0.0001
    max: 0.5
  learning_rate:
    min: 0.0001
    max: 0.1
  num_of_epochs:
    value: 100
  optimised:
    values: ['adam', 'sgd']
    