program: scripts/routines/dim_of_rectangular_drum.py
project: kac_prediction (rectangular drum dim)
method: random
metric:
  goal: minimize
  name: testing_loss.aggregate
parameters:
  batch_size:
    values: [8, 12, 16, 24, 32, 64, 5000]
  depth:
    values: ['large', 'medium', 'small', 'tiny']
  dropout:
    min: 0.0001
    max: 0.5
  learning_rate:
    min: 0.0001
    max: 0.01
  num_of_epochs:
    value: 0
  optimiser:
    values: ['adam', 'sgd']
  with_early_stopping:
    value: True