program: scripts/routines/size_of_circular_drum.py
project: kac_prediction (circular drum size)
method: random
metric:
  goal: minimize
  name: testing_loss
parameters:
  batch_size:
    values: [1, 2, 4, 8, 12, 16, 24, 32, 64, 5000]
  depth:
    value: tiny
  dropout:
    min: 0.0001
    max: 0.25
  learning_rate:
    min: 0.0001
    max: 0.007
  num_of_epochs:
    value: 0
  optimiser:
    value: adam
  with_early_stopping:
    value: True
    